const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync(require('node:path').join(__dirname,'../game.js'),'utf8');
const adjust=src.slice(src.indexOf('function padAdjustRange('),src.indexOf('/* ---------- what an A press',src.indexOf('function padAdjustRange(')));
const tick=src.slice(src.indexOf('function padTick(dt){'),src.indexOf(' if(padFocus)padMark(null);',src.indexOf('function padTick(dt){')))+'}';
function harness(){const events=[],moves=[],clicks=[],host={contains:()=>true},context={padFocus:null,padHit:{},padNear:{},Event:class{constructor(type,options){this.type=type;this.bubbles=options.bubbles}},padPollButtons(){},padPanelOpen:()=>host,padMenuStep:(_h,d)=>moves.push(d),padMark(){},padBack(){}};vm.createContext(context);vm.runInContext(adjust+'\n'+tick+';this.api={padTick,padAdjustRange}',context);const range=(value='100',min='60',max='140',step='1')=>({tagName:'INPUT',type:'range',value,min,max,step,disabled:false,dispatchEvent:e=>events.push({type:e.type,bubbles:e.bubbles}),click:()=>clicks.push('range')});return {context,events,moves,clicks,range,...context.api};}
test('controller left/right changes a focused range and emits native input/change events without navigating away',()=>{const h=harness();h.context.padFocus=h.range();h.context.padHit={right:true};h.padTick(.016);assert.equal(h.context.padFocus.value,'101');assert.deepEqual(h.events,[{type:'input',bubbles:true},{type:'change',bubbles:true}]);assert.deepEqual(h.moves,[]);h.context.padHit={left:true};h.padTick(.016);assert.equal(h.context.padFocus.value,'100');});
test('range bounds and declared steps are respected without redundant writes at either limit',()=>{const h=harness();h.context.padFocus=h.range('139','60','140','5');h.context.padHit={right:true};h.padTick(.016);assert.equal(h.context.padFocus.value,'140');h.padTick(.016);assert.equal(h.events.length,2);h.context.padFocus.value='61';h.context.padHit={left:true};h.padTick(.016);assert.equal(h.context.padFocus.value,'60');h.padTick(.016);assert.equal(h.events.length,4);});
test('up/down still leave sliders, and other controls retain their old left/right navigation and A click',()=>{const h=harness();h.context.padFocus=h.range();h.context.padHit={down:true};h.padTick(.016);h.context.padHit={up:true};h.padTick(.016);assert.deepEqual(h.moves,[1,-1]);assert.equal(h.context.padFocus.value,'100');h.context.padFocus={tagName:'BUTTON',click:()=>h.clicks.push('button')};h.context.padHit={right:true};h.padTick(.016);h.context.padHit={left:true};h.padTick(.016);h.context.padHit={a:true};h.padTick(.016);assert.deepEqual(h.moves,[1,-1,1,-1]);assert.deepEqual(h.clicks,['button']);assert.deepEqual(h.events,[]);});
test('disabled and nonrange inputs cannot be adjusted, while a standard audio slider uses its implicit step',()=>{const h=harness();const r=h.range('50','0','100','');h.context.padFocus=r;assert.equal(h.padAdjustRange(1),true);assert.equal(r.value,'51');r.disabled=true;assert.equal(h.padAdjustRange(1),false);r.disabled=false;r.type='checkbox';assert.equal(h.padAdjustRange(-1),false);assert.equal(r.value,'51');});
