(()=>{'use strict';
const data=window.TIDE_BREEDING_DATA,el=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
if(!data){el('progress').textContent='Katalogdata saknas. Öppna katalogen efter att bildlistan skapats.';return;}
const species=new Map(data.species.map(s=>[s.id,s])),sheets=new Map(data.sheets.map(s=>[s.id,s])),size=60;let page=0,filtered=[],selected=null,lastFocus=null;
let clipCounter=0;
function frame(art,label){if(!art||!art.file)return '<div class="pending">Bild skapas i Higgsfield</div>';const [x,y,w,h]=art.rect||[0,0,art.width,art.height],clip='sprite-clip-'+(++clipCounter),clipShape=art.clipPathD?`<path d="${esc(art.clipPathD)}" clip-rule="evenodd" fill-rule="evenodd"/>`:`<rect x="${x}" y="${y}" width="${w}" height="${h}"/>`;return `<svg class="sprite" viewBox="${x} ${y} ${w} ${h}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="${esc(label)}"><defs><clipPath id="${clip}" clipPathUnits="userSpaceOnUse">${clipShape}</clipPath></defs><image href="${esc(art.file)}" x="0" y="0" width="${art.width}" height="${art.height}" clip-path="url(#${clip})"/></svg>`;}
function art(h){const s=sheets.get(h.sheetId);if(s?.status!=='completed')return null;const cw=s.width/s.columns,ch=s.height/s.rows;return {...s,rect:h.rect||[h.cell%s.columns*cw,Math.floor(h.cell/s.columns)*ch,cw,ch],clipPathD:h.clipPathD};}
function pair(h){return species.get(h.parentA).name+' × '+species.get(h.parentB).name;}
for(const s of data.species){for(const id of ['parentA','parentB']){const option=document.createElement('option');option.value=s.id;option.textContent=s.name;el(id).append(option);}}
const complete=data.hybrids.filter(h=>sheets.get(h.sheetId)?.status==='completed').length;el('progress').textContent=`${complete} av ${data.hybrids.length} konceptbilder klara · Skapade med Higgsfield`;
function render(){const q=el('search').value.trim().toLocaleLowerCase('sv'),a=el('parentA').value,b=el('parentB').value;filtered=data.hybrids.filter(h=>{const ids=[h.parentA,h.parentB];return (!a||ids.includes(a))&&(!b||ids.includes(b))&&(!a||a!==b)&&(!q||[h.name,pair(h),h.descriptionSv].join(' ').toLocaleLowerCase('sv').includes(q));});page=Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1));
el('grid').innerHTML=filtered.slice(page*size,(page+1)*size).map(h=>`<button class="card" data-id="${h.id}" aria-label="Visa ${esc(h.name)}, ${esc(pair(h))}"><div class="card-art"><span class="number">${String(data.hybrids.indexOf(h)+1).padStart(3,'0')}</span>${frame(art(h),h.name)}</div><div class="card-info"><strong>${esc(h.name)}</strong><small>${esc(pair(h))}</small></div></button>`).join('');
el('resultCount').textContent=`${filtered.length} korsningar`;el('empty').hidden=!!filtered.length;el('pageInfo').textContent=`Sida ${page+1} av ${Math.max(1,Math.ceil(filtered.length/size))}`;el('previousPage').disabled=page===0;el('nextPage').disabled=(page+1)*size>=filtered.length;}
function open(id){const h=data.hybrids.find(x=>x.id===id);if(!h)return;selected=h.id;el('largeArt').innerHTML=frame(art(h),h.name);el('detailName').textContent=h.name;el('detailPair').textContent=pair(h);el('detailDescription').textContent=h.descriptionSv;el('parents').innerHTML=[h.parentA,h.parentB].map(id=>{const p=species.get(id);return `<div class="parent"><div class="parent-art">${frame(p.art,p.name)}</div><span>${esc(p.name)}</span></div>`;}).join('');const sheet=sheets.get(h.sheetId);el('sheetLink').hidden=sheet?.status!=='completed';el('sheetLink').href=sheet?.file||'#';const i=filtered.findIndex(x=>x.id===id);el('detailPosition').textContent=`${i+1} / ${filtered.length}`;el('previousDetail').disabled=i<=0;el('nextDetail').disabled=i>=filtered.length-1;if(!el('detail').open){lastFocus=document.activeElement;el('detail').showModal();}el('detail').scrollTop=0;}
function adjacent(delta){const i=filtered.findIndex(x=>x.id===selected);if(filtered[i+delta])open(filtered[i+delta].id);}
el('grid').addEventListener('click',e=>{const card=e.target.closest('[data-id]');if(card)open(card.dataset.id);});
for(const id of ['search','parentA','parentB'])el(id).addEventListener(id==='search'?'input':'change',()=>{page=0;render();});el('reset').onclick=()=>{for(const id of ['search','parentA','parentB'])el(id).value='';page=0;render();};
el('previousPage').onclick=()=>{page--;render();el('grid').scrollIntoView({block:'start'});};el('nextPage').onclick=()=>{page++;render();el('grid').scrollIntoView({block:'start'});};el('closeDetail').onclick=()=>el('detail').close();el('detail').addEventListener('close',()=>lastFocus?.focus());el('detail').addEventListener('click',e=>{if(e.target===el('detail')){const r=el('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)el('detail').close();}});el('previousDetail').onclick=()=>adjacent(-1);el('nextDetail').onclick=()=>adjacent(1);document.addEventListener('keydown',e=>{if(el('detail').open&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();adjacent(e.key==='ArrowLeft'?-1:1);}});render();
})();
